### PR TITLE
Support for codes in spec

### LINKED ISSUE #4: Doesn't follow the table
Table is not complete/finished, but the table in this module doesn't follow:

https://github.com/multiformats/multicodec/blob/master/multicodec-packed.md#standard-mcp-protocol-table

### PR DESCRIPTION
**Pull request by tabrath**
Ethereum, Stellar, Torrent codecs and Multiformat codecs. Added test cases too. Closes #4.

### CODE REVIEW

**Review by Kubuxu — APPROVED** [review]
Awesome, LGTM

**Comment by tabrath** [comment]
@whyrusleeping this pr includes ethereum codes, but I see you commited (07b394e2bc36bd37559456b1ac6138ac590f040e) after I commited this pr, Should I remove the ethereum codecs in this pr? The only difference is you used the short name (eth) and I used the full name (ethereum).

**Comment by whyrusleeping** [comment]
@tabrath Oh, sorry for committing that over you. Yeah, if you want to remove the ethereum names that would be great. I named them with just the `Eth` prefix to align a bit better with the javascript codes

**Comment by tabrath** [comment]
Alright, will do that. 👍

**Comment by tabrath** [comment]
@whyrusleeping Removed my eth codes and cleaned up a little.

**Pull request merged**
